### ISSUE TITLE
hydra-dired/body key binding conflicts

### ISSUE THREAD

**Issue by Ynjxsjmh** [redguardtoo/emacs.d#822]
https://github.com/redguardtoo/emacs.d/blob/master/lisp/init-hydra.el#L233

```
^Misc^                      ^File^              ^Copy Info^
-----------------------------------------------------------------
[_vv_] video2mp3            [_R_] Move          [_pp_] Path
[_aa_] Record by mp3        [_cf_] New          [_nn_] Name
[_zz_] Play wav&mp3         [_rr_] Rename       [_bb_] Base
[_cc_] Last command         [_ff_] Find         [_dd_] directory
[_sa_] Fetch all subtitles  [_C_]  Copy
[_s1_] Fetch on subtitle    [_rb_] Change base
[_+_] Create directory      [_dd_] Diff 2 files
```

There exist two `dd`

**Comment by Ynjxsjmh** [comment]
After using `y` to pop up the hydra, `pp`, `nn` or `bb` will trigger the warning `cond: Cannot open load file: No such file or directory, xclip`.

`toggle-debug-on-error` gives me the backtrace

```
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "xclip")
  (xclip-set-selection 'clipboard str-val)
  (cond ((and win64-clip-program (memq system-type '(gnu gnu/linux gnu/kfreebsd))) (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (insert str-val) (call-process-region (point-min) (point-max) win64-clip-program)) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))))) (t (xclip-set-selection 'clipboard str-val)))
  (let* ((win64-clip-program (executable-find "clip.exe"))) (cond ((and win64-clip-program (memq system-type '(gnu gnu/linux gnu/kfreebsd))) (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (insert str-val) (call-process-region (point-min) (point-max) win64-clip-program)) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))))) (t (xclip-set-selection 'clipboard str-val))))
  my-pclip("e:/sourcecode/Toolkit/icourse163/analyse.org.org")
  copy-yank-str("e:/sourcecode/Toolkit/icourse163/analyse.org.org")
  (message "%s => clipboard & yank ring" (copy-yank-str (funcall fn (dired-file-name-at-point))))
  my-copy-file-info(file-truename)
  (closure (t) nil (interactive) (my-copy-file-info 'file-truename))()
  funcall-interactively((closure (t) nil (interactive) (my-copy-file-info 'file-truename)))
  call-interactively((closure (t) nil (interactive) (my-copy-file-info 'file-truename)))
  hydra--call-interactively-remap-maybe((closure (t) nil (interactive) (my-copy-file-info 'file-truename)))
  hydra-dired/lambda-pp-and-exit()
  funcall-interactively(hydra-dired/lambda-pp-and-exit)
  call-interactively(hydra-dired/lambda-pp-and-exit nil nil)
  command-execute(hydra-dired/lambda-pp-and-exit)
```

**Comment by redguardtoo** [comment]
fixed hotkey, but can't reproduce xclip issue,

Run `C-h v load-path`, you should find xclip's path and make sure `xclip.el` exist.

![image](https://user-images.githubusercontent.com/184553/77895956-3dd85b80-72c3-11ea-9c0b-921648d2c983.png)

**Comment by Ynjxsjmh** [comment]
I couldn't find anything related with `~/site-lisp` except those in my emacs installed path.

![image](https://user-images.githubusercontent.com/40143136/77898098-373ee980-72ad-11ea-8727-59859a31c2e9.png)

A quick search `site-lisp` between your and mine

https://github.com/redguardtoo/emacs.d/search?q=site-lisp&unscoped_q=site-lisp

https://github.com/Ynjxsjmh/.emacs.d/search?q=site-lisp&unscoped_q=site-lisp

I pulled from your .emacs.d yesterday and last time is on  14 Sep 2019. I didn't get any warning using that config.

**Comment by redguardtoo** [comment]
https://github.com/Ynjxsjmh/.emacs.d/blob/master/site-lisp/xclip/xclip.el It's there.

**Comment by Ynjxsjmh** [comment]
Thank you for your patience, I suddenly remember my emacs is not well started up this morning. After restarting my emacs, checking `load-path` again, packages under `~/.emacs.d/site-lisp` appear in load-path and I don't get the warning.

**Comment by Ynjxsjmh** [comment]
> fixed hotkey

https://github.com/redguardtoo/emacs.d/blob/7e43c3bfcb30eb418e53ab1dc8a2f6f241628575/lisp/init-hydra.el#L275-L280

https://github.com/redguardtoo/emacs.d/blob/7e43c3bfcb30eb418e53ab1dc8a2f6f241628575/lisp/init-hydra.el#L299

Although hotkey conflict is fixed, the tip in popup is not fixed.

**Comment by redguardtoo** [comment]
77000b1a fixed doc (Chen Bin)
